CREATE CONSTRAINT repository_id IF NOT EXISTS
FOR (n:Repository) REQUIRE n.id IS UNIQUE;

CREATE CONSTRAINT commit_id IF NOT EXISTS
FOR (n:Commit) REQUIRE n.id IS UNIQUE;

CREATE CONSTRAINT pull_request_id IF NOT EXISTS
FOR (n:PullRequest) REQUIRE n.id IS UNIQUE;

CREATE CONSTRAINT issue_id IF NOT EXISTS
FOR (n:Issue) REQUIRE n.id IS UNIQUE;

CREATE CONSTRAINT developer_id IF NOT EXISTS
FOR (n:Developer) REQUIRE n.id IS UNIQUE;

CREATE CONSTRAINT file_id IF NOT EXISTS
FOR (n:File) REQUIRE n.id IS UNIQUE;
